version : "3"

services:
  java-service:
    build: .
    container_name: "java-service-container"
    ports:
      - "8787:8787"
    depends_on:
      - postgesql
      - rabbit-mq
    environment:
      - POSTGRES_DATABASE=test
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST=172.20.0.6
      - POSTGRES_PORT=5432
      - RABBIT_HOST=172.20.0.4
      - RABBIT_PORT=5672
    networks:
      vpcbr:
        ipv4_address: 172.20.0.5


  postgesql:
    image: postgres
    container_name: "postgres-container"

    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test
    volumes:
      - /home/andrew/psql_railway_datastorage:/var/lib/postgresql/data
    networks:
      vpcbr:
        ipv4_address: 172.20.0.6


  rabbit-mq:
    image : rabbitmq:3-management
    container_name: "rabbit-mq"
    networks:
      vpcbr:
        ipv4_address: 172.20.0.4


networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

