spring:
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: guest
    password: guest

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate.connection.release_mode: after_transaction
        hibernate.transaction.auto_close_session: true
        hibernate.autoReconnect: true
        hibernate.connection.autocommit: false
        enable_lazy_load_no_trans: true
        max_fetch_depth: 1
        temp:
          use_jdbc_metadata_defaults: false

server:
  port: 8787
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
  servlet:
    session:
      timeout: 1728000
  connection-timeout: 10000000
logging.file: logs/log.txt
logging:
  file:
    max-history: 20
    max-size: 10MB
  level:
    com.zpoken.dashboarddsa: debug





